# Javascript Node CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/repo

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-node-{{ .Branch }}-{{ .Revision }}
            - v1-node-{{ .Branch }}-
            - v1-node-
      - checkout
      - save_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo"

  install_dependencies:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - depens-{{ checksum "package.json" }}
            - depens-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: depens-{{ checksum "package.json" }}
  
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json
  
  unit_tests:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - run: yarn test
        environment:
          NODE_OPTIONS: --max_old_space_size=8192
    
  e2e_tests:
    docker:
      - image: cypress/base:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run:  yarn e2e-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - build
      - e2e_tests:
          requires:
            - build
