# Javascript Node CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/repo

version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-node-{{ .Branch }}-{{ .Revision }}
            - v1-node-{{ .Branch }}-
            - v1-node-
      - checkout
      - save_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo"

  install_dependencies:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - depens-{{ checksum "package.json" }}
            - depens-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: depens-{{ checksum "package.json" }}
  
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json
  
  unit_tests:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-node-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - run: yarn test

  e2e_tests:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run: $(yarn bin)/cypress run --record --key 5aa4cb38-1b2c-4335-9cb1-7d547572ee4

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
      - e2e_tests
