# Javascript Node CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json
  
  test:
    <<: *defaults
    steps:
      - run: yarn test:badges
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
