version: 2
jobs:
  build:
    docker:
      - image: cypress/base:6
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: /var/www
    steps:
      - checkout
      - run: npm install
      - sleep 240
      - run: $(npm bin)/cypress run --record --key 5aa4cb38-1b2c-4335-9cb1-7d547572ee4a
      